# Generated by Django 6.0 on 2026-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_Name', models.CharField(max_length=200)),
                ('game_rating', models.IntegerField()),
                ('game_details', models.CharField()),
            ],
        ),
    ]
